apiVersion: v1
kind: ConfigMap
metadata:
  name: procureai-config
  namespace: procureai
data:
  DB_HOST: "procureai-postgres"
  DB_PORT: "5432"
  DB_USER: "admin"
  REDIS_HOST: "procureai-redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "procureai-rabbitmq"
  MINIO_ENDPOINT: "http://procureai-minio:9000"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
  SERVICE_GATEWAY_URL: "http://api-gateway:8082"
  SERVICE_AUTH_URL: "http://auth-service:8081"
  SERVICE_USER_URL: "http://user-service:8090"
  SERVICE_PROCUREMENT_URL: "http://procurement-service:8088"
  SERVICE_RFQ_URL: "http://rfq-service:8083"
  SERVICE_QUOTATION_URL: "http://quotation-service:8084"
  SERVICE_SUPPLIER_URL: "http://supplier-service:8085"
  SERVICE_INVOICE_URL: "http://invoice-service:8086"
  SERVICE_NOTIFICATION_URL: "http://notification-service:8087"
  NEXT_PUBLIC_API_URL: "https://api.procureai.com"
