server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: procurement-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/procurement_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:supersecretpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    auth:
      url: ${AUTH_DATABASE_URL:jdbc:postgresql://localhost:5432/auth_db}
      username: ${AUTH_DB_USERNAME:admin}
      password: ${AUTH_DB_PASSWORD:supersecretpassword}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
